# Disk Performance Calculations
# Implements formulas from sec-2-1.pdf (Information Storage Course)
"""
Disk Performance Module
======================
Implements disk drive performance calculations from course materials:
- Service Time (Ts): seek time + rotational latency + transfer time
- IOPS: Input/Output Operations Per Second
- Disk Capacity Requirements (Dc)
- Disk Performance Requirements (Dp)

Formulas based on sec-2-1.pdf slides 5-6
"""

import math


def calculate_service_time(seek_time_ms, disk_rpm, data_block_size_kb, transfer_rate_mbps):
    """
    Calculate disk service time using the formula from sec-2-1.pdf slide 5:
    Ts = seek_time + (0.5 / (disk_rpm / 60)) + (data_block_size / transfer_rate)
    
    Args:
        seek_time_ms: Average seek time in milliseconds
        disk_rpm: Disk rotation speed in RPM (rotations per minute)
        data_block_size_kb: Size of data block in kilobytes
        transfer_rate_mbps: Data transfer rate in MB/s
    
    Returns:
        Service time in milliseconds
    
    Example:
        >>> # From sec-2-1.pdf slide 14: 15K RPM disk, 5ms seek, 4KB block, 40MB/s
        >>> ts = calculate_service_time(5, 15000, 4, 40)
        >>> print(f"Service time: {ts:.2f} ms")
        Service time: 7.10 ms
    """
    # Calculate rotational latency: 0.5 / (rpm / 60)
    # Convert to milliseconds: * 1000
    rotational_latency_ms = (0.5 / (disk_rpm / 60)) * 1000
    
    # Calculate transfer time: data_size / transfer_rate
    # Convert KB to MB: divide by 1024
    # Result is in seconds, convert to ms: * 1000
    data_block_size_mb = data_block_size_kb / 1024
    transfer_time_ms = (data_block_size_mb / transfer_rate_mbps) * 1000
    
    # Total service time
    service_time = seek_time_ms + rotational_latency_ms + transfer_time_ms
    
    return service_time


def calculate_iops(service_time_ms, utilization=1.0):
    """
    Calculate IOPS (Input/Output Operations Per Second) from service time.
    Formula from sec-2-1.pdf slide 6:
    IOPS = 1 / (Ts * 0.001)
    
    For performance-sensitive applications, use 70% utilization:
    IOPS = 0.7 * (1 / (Ts * 0.001))
    
    Args:
        service_time_ms: Disk service time in milliseconds
        utilization: Disk utilization factor (0.7 for 70% utilization, 1.0 for 100%)
    
    Returns:
        IOPS (operations per second)
    
    Example:
        >>> # Full utilization
        >>> iops_100 = calculate_iops(7.1, utilization=1.0)
        >>> print(f"100% utilization: {iops_100:.0f} IOPS")
        100% utilization: 140 IOPS
        >>> 
        >>> # 70% utilization (recommended for acceptable response time)
        >>> iops_70 = calculate_iops(7.1, utilization=0.7)
        >>> print(f"70% utilization: {iops_70:.0f} IOPS")
        70% utilization: 98 IOPS
    """
    # Convert service time from ms to seconds
    service_time_s = service_time_ms * 0.001
    
    # Calculate IOPS with utilization factor
    iops = utilization * (1 / service_time_s)
    
    return iops


def calculate_disk_capacity_required(total_capacity_gb, disk_capacity_gb):
    """
    Calculate number of disks required to meet capacity needs.
    Formula from sec-2-1.pdf slide 6:
    Dc = total_capacity_required / capacity_of_single_disk
    
    Args:
        total_capacity_gb: Total storage capacity required in GB
        disk_capacity_gb: Capacity of a single disk in GB
    
    Returns:
        Number of disks required (rounded up)
    
    Example:
        >>> # From sec-2-1.pdf slide 16: 1TB data, 100GB disks
        >>> dc = calculate_disk_capacity_required(1024, 100)
        >>> print(f"Disks required for capacity: {dc}")
        Disks required for capacity: 10
    """
    return math.ceil(total_capacity_gb / disk_capacity_gb)


def calculate_disk_performance_required(app_iops, disk_iops):
    """
    Calculate number of disks required to meet performance needs.
    Formula from sec-2-1.pdf slide 6:
    Dp = IOPS_generated_by_application / IOPS_serviced_by_single_disk
    
    Args:
        app_iops: IOPS generated by application at peak workload
        disk_iops: IOPS that a single disk can service
    
    Returns:
        Number of disks required (rounded up)
    
    Example:
        >>> # From sec-2-1.pdf slide 15: 4900 IOPS app, 98 IOPS per disk (70% util)
        >>> dp = calculate_disk_performance_required(4900, 98)
        >>> print(f"Disks required for performance: {dp}")
        Disks required for performance: 50
    """
    return math.ceil(app_iops / disk_iops)


def calculate_total_disks_required(total_capacity_gb, disk_capacity_gb, app_iops, disk_iops):
    """
    Calculate total number of disks required for an application.
    Formula from sec-2-1.pdf slide 16:
    Total disks = max(Dc, Dp)
    
    The application needs the MAXIMUM of capacity or performance requirements.
    
    Args:
        total_capacity_gb: Total storage capacity required in GB
        disk_capacity_gb: Capacity of a single disk in GB
        app_iops: IOPS generated by application at peak workload
        disk_iops: IOPS that a single disk can service
    
    Returns:
        Dictionary with:
        - disks_for_capacity: Number of disks needed for capacity
        - disks_for_performance: Number of disks needed for performance
        - total_disks_required: Maximum of the two (actual requirement)
    
    Example:
        >>> # Complete example from sec-2-1.pdf slides 13-16
        >>> result = calculate_total_disks_required(
        ...     total_capacity_gb=1024,  # 1TB
        ...     disk_capacity_gb=100,     # 100GB per disk
        ...     app_iops=4900,            # Application needs 4900 IOPS
        ...     disk_iops=98              # Each disk provides 98 IOPS (70% util)
        ... )
        >>> print(f"Capacity requirement: {result['disks_for_capacity']} disks")
        >>> print(f"Performance requirement: {result['disks_for_performance']} disks")
        >>> print(f"Total required: {result['total_disks_required']} disks")
        Capacity requirement: 10 disks
        Performance requirement: 50 disks
        Total required: 50 disks
    """
    dc = calculate_disk_capacity_required(total_capacity_gb, disk_capacity_gb)
    dp = calculate_disk_performance_required(app_iops, disk_iops)
    
    return {
        "disks_for_capacity": dc,
        "disks_for_performance": dp,
        "total_disks_required": max(dc, dp)
    }


def calculate_rotational_latency(disk_rpm):
    """
    Calculate average rotational latency for a disk.
    Formula from sec-2-1.pdf slide 8:
    Average Rotational Latency = (1/2) * (60000 / RPM) milliseconds
    
    Args:
        disk_rpm: Disk rotation speed in RPM
    
    Returns:
        Average rotational latency in milliseconds
    
    Example:
        >>> # From sec-2-1.pdf slide 8: 7200 RPM disk
        >>> latency = calculate_rotational_latency(7200)
        >>> print(f"Average rotational latency: {latency:.2f} ms")
        Average rotational latency: 4.17 ms
    """
    return 0.5 * (60000 / disk_rpm)


def complete_disk_analysis(seek_time_ms, disk_rpm, data_block_size_kb, 
                          transfer_rate_mbps, total_capacity_gb, 
                          disk_capacity_gb, app_iops_required):
    """
    Perform complete disk performance analysis matching sec-2-1.pdf example.
    
    This combines all formulas to solve the complete problem from slides 13-16.
    
    Args:
        seek_time_ms: Average seek time in milliseconds
        disk_rpm: Disk rotation speed in RPM
        data_block_size_kb: Size of data block in KB
        transfer_rate_mbps: Data transfer rate in MB/s
        total_capacity_gb: Total storage capacity required
        disk_capacity_gb: Capacity of single disk
        app_iops_required: IOPS required by application
    
    Returns:
        Dictionary with complete analysis results
    
    Example:
        >>> # Complete scenario from sec-2-1.pdf slides 13-16
        >>> analysis = complete_disk_analysis(
        ...     seek_time_ms=5,
        ...     disk_rpm=15000,
        ...     data_block_size_kb=4,
        ...     transfer_rate_mbps=40,
        ...     total_capacity_gb=1024,
        ...     disk_capacity_gb=100,
        ...     app_iops_required=4900
        ... )
        >>> print(f"Service Time: {analysis['service_time_ms']:.2f} ms")
        >>> print(f"IOPS (70% util): {analysis['iops_70_percent']:.0f}")
        >>> print(f"Total disks required: {analysis['total_disks_required']}")
        Service Time: 7.10 ms
        IOPS (70% util): 98
        Total disks required: 50
    """
    # Step 1: Calculate service time
    ts = calculate_service_time(seek_time_ms, disk_rpm, data_block_size_kb, transfer_rate_mbps)
    
    # Step 2: Calculate IOPS for both utilization levels
    iops_100 = calculate_iops(ts, utilization=1.0)
    iops_70 = calculate_iops(ts, utilization=0.7)
    
    # Step 3: Calculate disk requirements
    disk_reqs = calculate_total_disks_required(
        total_capacity_gb, 
        disk_capacity_gb, 
        app_iops_required, 
        iops_70  # Use 70% utilization for acceptable response time
    )
    
    return {
        "service_time_ms": ts,
        "rotational_latency_ms": calculate_rotational_latency(disk_rpm),
        "iops_100_percent": iops_100,
        "iops_70_percent": iops_70,
        "disks_for_capacity": disk_reqs["disks_for_capacity"],
        "disks_for_performance": disk_reqs["disks_for_performance"],
        "total_disks_required": disk_reqs["total_disks_required"]
    }


if __name__ == "__main__":
    # Example from sec-2-1.pdf slides 13-16
    print("=" * 60)
    print("Disk Performance Analysis (from sec-2-1.pdf)")
    print("=" * 60)
    
    result = complete_disk_analysis(
        seek_time_ms=5,
        disk_rpm=15000,
        data_block_size_kb=4,
        transfer_rate_mbps=40,
        total_capacity_gb=1024,
        disk_capacity_gb=100,
        app_iops_required=4900
    )
    
    print(f"\nDisk Specifications:")
    print(f"  - 15K RPM drive")
    print(f"  - 100 GB capacity")
    print(f"  - 5ms seek time")
    print(f"  - 40 MB/s transfer rate")
    
    print(f"\nApplication Requirements:")
    print(f"  - 1TB storage")
    print(f"  - 4900 IOPS")
    print(f"  - 4KB I/O size")
    
    print(f"\nCalculated Metrics:")
    print(f"  Service Time: {result['service_time_ms']:.2f} ms")
    print(f"  Rotational Latency: {result['rotational_latency_ms']:.2f} ms")
    print(f"  IOPS (100% util): {result['iops_100_percent']:.0f}")
    print(f"  IOPS (70% util): {result['iops_70_percent']:.0f}")
    
    print(f"\nDisk Requirements:")
    print(f"  For Capacity (Dc): {result['disks_for_capacity']} disks")
    print(f"  For Performance (Dp): {result['disks_for_performance']} disks")
    print(f"  Total Required: {result['total_disks_required']} disks")
    print(f"\n  → Performance is the bottleneck (need {result['total_disks_required']} disks)")
